name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Capacitor & Android build tools
      run: |
        npm install
        npm install -g @capacitor/cli
        npm install @capacitor/android
        npx cap init --web-dir=./
        npx cap add android

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: macxrewardsapp-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
