name: Build Android APK - macxrewardsapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Project Dependencies
      run: |
        npm install
        npm install -g @capacitor/cli
        npm install @capacitor/android
        npx cap sync

    - name: Add Android Platform (if not already)
      run: |
        npx cap add android || echo "Android already exists"

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: List APK output files
      run: |
        ls -R android/app/build/outputs/apk/debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macxrewardsapp-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
